export const pricing = {
  monthly: [
    {
      name: "Starter",
      price: 0,
      description: "Perfect for individuals building their first forms.",
      cta: "Start Free",
      href: "/signup",
      featured: false,
      features: [
        "Unlimited forms",
        "100 submissions / month",
        "Basic analytics",
        "Community support",
      ],
    },
    {
      name: "Pro",
      price: 29,
      description: "Built for growing teams shipping at scale.",
      cta: "Upgrade to Pro",
      href: "/signup",
      featured: true,
      features: [
        "Unlimited submissions",
        "Advanced analytics",
        "Custom themes",
        "Logic branching",
        "Webhook integrations",
        "Priority support",
      ],
    },
    {
      name: "Enterprise",
      price: 99,
      description: "Advanced workflows for large organizations.",
      cta: "Contact Sales",
      href: "/contact",
      featured: false,
      features: [
        "Everything in Pro",
        "SSO + SAML",
        "Audit logs",
        "Dedicated infrastructure",
        "Custom SLAs",
        "Team permissions",
      ],
    },
  ],

  yearly: [
    {
      name: "Starter",
      price: 0,
      description: "Perfect for individuals building their first forms.",
      cta: "Start Free",
      href: "/signup",
      featured: false,
      features: [
        "Unlimited forms",
        "100 submissions / month",
        "Basic analytics",
        "Community support",
      ],
    },
    {
      name: "Pro",
      price: 24,
      description: "Save more with annual billing.",
      cta: "Upgrade to Pro",
      href: "/signup",
      featured: true,
      features: [
        "Unlimited submissions",
        "Advanced analytics",
        "Custom themes",
        "Logic branching",
        "Webhook integrations",
        "Priority support",
      ],
    },
    {
      name: "Enterprise",
      price: 89,
      description: "Enterprise-grade deployment at scale.",
      cta: "Contact Sales",
      href: "/contact",
      featured: false,
      features: [
        "Everything in Pro",
        "SSO + SAML",
        "Audit logs",
        "Dedicated infrastructure",
        "Custom SLAs",
        "Team permissions",
      ],
    },
  ],
};
