-- Snapshot alignment migration generated by drizzle-kit.
-- This migration does not change the schema; it simply
-- satisfies the migration journal entry for tag
-- "0005_thankful_champions" so that future migrations
-- can run without errors.

SELECT 1;--> statement-breakpoint

